environment: production
type: beta

discovery:
  operator:
    evm_address: 0x8725eb313134e592cd573b82887423ff24c9f23b
    signature:
  server:
    endpoint:
    global_indexer_endpoint: https://gi.rss3.io/
    access_token: test

database:
  driver: postgres
  partition: true
  uri: postgres://postgres:password@localhost:5432/postgres

stream:
  enable: false
  driver: kafka
  topic: rss3.node.activities
  uri: localhost:9092

redis:
  endpoints:
    - localhost:6379
  username:
  password:
  disable_cache: true
  tls:
    enabled: false
    ca_file: /path/to/ca.crt
    cert_file: /path/to/client.crt
    key_file: /path/to/client.key
    insecure_skip_verify: false

observability:
  opentelemetry:
    metrics:
      enable: true
      endpoint: 0.0.0.0:9090
    traces:
      enable: true
      insecure: true
      endpoint: localhost:4318

endpoints:
  mastodon:
    url: 34.16.147.19:9092
  farcaster:
    url: https://farcaster.mainnet.rss3.io
  ethereum:
    url: https://ethereum.blockpi.network/v1/rpc/4926ff8018353b261139b1ec6ea7b7ec5cc5d692
  polygon:
    url: https://rpc.ankr.com/polygon
  avax:
    url: https://rpc.ankr.com/avalanche
  optimism:
    url: https://rpc.ankr.com/optimism
  arbitrum:
    url: https://rpc.ankr.com/arbitrum
  gnosis:
    url: https://rpc.ankr.com/gnosis
  linea:
    url: https://rpc.linea.build
  savm:
    url: https://alpha-rpc-node-http.svmscan.io
  binance-smart-chain:
    url: https://rpc.ankr.com/bsc
  base:
    url: https://rpc.ankr.com/base
    http2_disabled: true
  crossbell:
    url: https://rpc.crossbell.io
  vsl:
    url: https://rpc.rss3.io
  arweave:
    url: https://arweave.net
component:
#  rss:
#    network: rss
#    endpoint: https://rsshub.app/
#    worker: rsshub
#    parameters:
#      authentication:
#      access_key:
  federated:
    - id: mastodon-core
      network: mastodon
      worker: mastodon
      endpoint: mastodon
      parameters:
        kafka_topic: activitypub_events
  decentralized:
    - id: ethereum-core
      network: ethereum
      worker: core
      endpoint: ethereum
      parameters:
        block_start:
#    - id: ethereum-uniswap
#      network: ethereum
#      worker: uniswap
#      endpoint: ethereum
#      parameters:
#        block_start: 19977617
#    - id: ethereum-rss3
#      network: ethereum
#      worker: rss3
#      endpoint: ethereum
#      parameters:
#        block_start:
#        block_target:
#    - id: polygon-lens
#      network: polygon
#      worker: lens
#      endpoint: polygon
#      ipfs_gate logways:
#      parameters:
#        block_start:
#    - id: ethereum-opensea
#      network: ethereum
#      worker: opensea
#      endpoint: ethereum
#      parameters:
#        block_start:
#    - id: ethereum-optimism
#      network: ethereum
#      worker: optimism
#      endpoint: ethereum
#      parameters:
#        block_start:
#    - id: polygon-aavegotchi
#      network: polygon
#      worker: aavegotchi
#      endpoint: polygon
#      parameters:
#        block_start: 48300005
#    - id: ethereum-highlight
#      network: ethereum
#      worker: highlight
#      endpoint: ethereum
#      parameters:
#        block_start:
#    - id: arbitrum-highlight
#      network: arbitrum
#      worker: highlight
#      endpoint: arbitrum
#      parameters:
#        block_start:
#    - id: polygon-highlight
#      network: polygon
#      worker: highlight
#      endpoint: polygon
#      parameters:
#        block_start:
#    - id: optimism-highlight
#      network: optimism
#      worker: highlight
#      endpoint: optimism
#      parameters:
#        block_start:
#    - id: crossbell-crossbell
#      network: crossbell
#      worker: crossbell
#      endpoint: https://rpc.crossbell.io
#      parameters:
#        block_start:
#    # farcaster
#    - id: farcaster-core
#      network: farcaster
#      worker: core
#      endpoint: farcaster
#      parameters:
#        api_key:
#    # arweave
#    - id: arweave-mirror
#      network: arweave
#      endpoint: arweave
#      worker: mirror
#      ipfs_gateways:
#      parameters:
#        block_start:
#        concurrent_block_requests:
#    - id: arweave-paragraph
#      network: arweave
#      endpoint: arweave
#      worker: paragraph
#      ipfs_gateways:
#      parameters:
#        block_start:
#        concurrent_block_requests:
#    - id: ethereum-looksrare
#      network: ethereum
#      worker: looksrare
#      endpoint: ethereum
#      parameters:
#        block_start:
#    - id: optimism-matters
#      network: optimism
#      worker: matters
#      endpoint: optimism
#      parameters:
#        block_start:
#    - id: arweave-momoka
#      network: arweave
#      worker: momoka
#      endpoint: polygon
#      parameters:
#        block_start:
#        concurrent_block_requests:
#    - id: ethereum-aave
#      network: ethereum
#      endpoint: ethereum
#      worker: aave
#      parameters:
#        block_start:
#    - id: polygon-aave
#      network: polygon
#      endpoint: polygon
#      worker: aave
#      parameters:
#        block_start:
#    - id: avax-aave
#      network: avax
#      endpoint: avax
#      worker: aave
#      parameters:
#        block_start:
#    - id: base-aave
#      network: base
#      endpoint: base
#      worker: aave
#      parameters:
#        block_start:
#    - id: optimism-aave
#      network: optimism
#      endpoint: optimism
#      worker: aave
#      parameters:
#        block_start:
#    - id: arbitrum-aave
#      network: arbitrum
#      endpoint: arbitrum
#      worker: aave
#      parameters:
#        block_start:
#    - id: polygon-iqwiki
#      network: polygon
#      worker: iqwiki
#      endpoint: polygon
#      parameters:
#        block_start:
#    - id: ethereum-lido
#      network: ethereum
#      endpoint: ethereum
#      worker: lido
#      parameters:
#        block_start:
#    - id: ethereum-ens
#      network: ethereum
#      endpoint: ethereum
#      worker: ens
#      parameters:
#        block_start:
#    - id: ethereum-1inch
#      network: ethereum
#      worker: 1inch
#      endpoint: ethereum
#      parameters:
#        block_start:
#    - id: vsl-core
#      network: vsl
#      endpoint: vsl
#      worker: core
#      parameters:
#        block_start:
#    - id: optimism-kiwistand
#      network: optimism
#      endpoint: optimism
#      worker: kiwistand
#      parameters:
#        block_start:
#    - id: savm-core
#      network: savm
#      endpoint: savm
#      worker: core
#      parameters:
#        block_start:
#    - id: savm-uniswap
#      network: savm
#      endpoint: savm
#      worker: uniswap
#      parameters:
#        block_start:
#    - id: savm-savm
#      network: savm
#      endpoint: savm
#      worker: savm
#      parameters:
#        block_start:
#    - id: optimism-core
#      network: optimism
#      endpoint: optimism
#      worker: core
#      parameters:
#        block_start:
#    - id: polygon-core
#      network: polygon
#      endpoint: polygon
#      worker: core
#      parameters:
#        block_start:
#    - id: arbitrum-core
#      network: arbitrum
#      endpoint: arbitrum
#      worker: core
#      parameters:
#        block_start:
#    - id: base-core
#      network: base
#      endpoint: base
#      worker: core
#      parameters:
#        block_start:
#    - id: binance-smart-chain-core
#      network: binance-smart-chain
#      endpoint: binance-smart-chain
#      worker: core
#      parameters:
#        block_start: 34436412
#        concurrent_block_requests: 1
#    - id: gnosis-core
#      network: gnosis
#      endpoint: gnosis
#      worker: core
#      parameters:
#        block_start:
#    - id: linea-core
#      network: linea
#      endpoint: linea
#      worker: core
#      parameters:
#        block_start:
#    - id: linea-uniswap
#      network: linea
#      endpoint: linea
#      worker: uniswap
#      parameters:
#        block_start:
#    - id: vsl-rss3
#      network: vsl
#      endpoint: vsl
#      worker: rss3
#    - id: ethereum-vsl
#      network: ethereum
#      worker: vsl
#      endpoint: ethereum
#      parameters:
#        block_start:
#    - id: ethereum-stargate
#      network: ethereum
#      worker: stargate
#      endpoint: ethereum
#      parameters:
#        block_start:
#    - id: arbitrum-stargate
#      network: arbitrum
#      worker: stargate
#      endpoint: arbitrum
#      parameters:
#        block_start:
#    - id: linea-stargate
#      network: linea
#      endpoint: linea
#      worker: stargate
#      parameters:
#        block_start:
#    - id: binance-smart-chain-stargate
#      network: binance-smart-chain
#      endpoint: binance-smart-chain
#      worker: stargate
#      parameters:
#        block_start:
#    - id: base-stargate
#      network: base
#      endpoint: base
#      worker: stargate
#      parameters:
#        block_start:
#    - id: optimism-stargate
#      network: optimism
#      endpoint: optimism
#      worker: stargate
#      parameters:
#        block_start:
#    - id: polygon-stargate
#      network: polygon
#      worker: stargate
#      endpoint: polygon
#      parameters:
#        block_start:
#    - id: avax-stargate
#      network: avax
#      endpoint: avax
#      worker: stargate
#      parameters:
#        block_start:
#    - id: ethereum-curve
#      network: ethereum
#      worker: curve
#      endpoint: ethereum
#      parameters:
#        block_start:
#    - id: arbitrum-curve
#      network: arbitrum
#      worker: curve
#      endpoint: arbitrum
#      parameters:
#        block_start:
#    - id: avax-curve
#      network: avax
#      endpoint: avax
#      worker: curve
#      parameters:
#        block_start:
#    - id: gnosis-curve
#      network: gnosis
#      endpoint: gnosis
#      worker: curve
#      parameters:
#        block_start:
#    - id: optimism-curve
#      network: optimism
#      worker: curve
#      endpoint: optimism
#      parameters:
#        block_start:
#    - id: polygon-curve
#      network: polygon
#      worker: curve
#      endpoint: polygon
#      parameters:
#        block_start:
#